### ISSUE TITLE
Support for geonorge.no API v3

### ISSUE THREAD

**Issue by vpaturet** [halset/jskdata#5]
Hello and thank you for the library,
We noticed recently at Entur that support for the v2-API was broken on geonorge.no, probably since the v3-API was released ( this is the case at least for https://nedlasting.geonorge.no/api/v2/order).
Do you plan to support the v3-API in jskdata?

**Comment by halset** [comment]
We had an issue with authenticated login for GeoNorge after they moved from SAML to GeoID. New fix requires a special "basic auth" user to download authenticated datasets. To get that to work, we switched from apt/v2/order to just api/order. Can you try the new version?

**Comment by vpaturet** [comment]
We successfully integrated the new version, thanks!
